ARG BASE_IMAGE="registry.goldenhelix.com/public/ghdesktop-office-web:latest"
FROM $BASE_IMAGE AS base_layer

USER root

ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

######### Customize Container Here ###########

COPY  ./src/gh/install/oo_custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh \
  && chmod 755 $STARTUPDIR/custom_startup.sh

# Clear this if you don't want to shutdown the container if OnlyOffice exists
ENV MONITOR_PROCESS 1

######### End Customizations ###########

RUN chown 1000:0 $HOME

ENV HOME /home/ghuser
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
