ARG BASE_IMAGE="registry.goldenhelix.com/public/ghdesktop-office-web:latest"
FROM $BASE_IMAGE AS base_layer

USER root

ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

RUN apt-get update && apt-get install -y \
    unzip \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/igv

RUN curl -L "https://data.broadinstitute.org/igv/projects/downloads/2.16/IGV_Linux_2.16.0_WithJava.zip" -o /tmp/igv.zip \
    && unzip /tmp/igv.zip -d /tmp \
    && rm /tmp/igv.zip \
    && mv /tmp/IGV_Linux_2.16.0/* /opt/igv/ \
    && rmdir /tmp/IGV_Linux_2.16.0 \
    && chmod +x /opt/igv/igv.sh

# Set the PATH to include the bundled Java
ENV PATH="/opt/igv/java/bin:${PATH}"

RUN chmod +x /opt/igv/igv.sh

COPY  ./src/gh/install/igv_custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh \
    && chmod 755 $STARTUPDIR/custom_startup.sh

# Clear this if you don't want to shutdown the container if OnlyOffice exists
ENV MONITOR_PROCESS 1

RUN chown 1000:0 $HOME

ENV HOME /home/ghuser
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
